# Analiza zbioru statystyk siatkarzy z VNL 2021-2023 i próba predykcji czy siatkarz z danymi statystykami wygra mecz

## Prezentacja statystyk jakie posiada jeden zawodnik

```{r}
setwd("../")
data <- read.csv("vnl_dataset.csv")
data$Winner <- data$Winner == "True"
data$Position <- factor(data$Position)
data$Nationality <- factor(data$Nationality)


filtered_data <- data[data$Player.Name == "Sliwka Aleksander", ]
print(filtered_data)
```

## Przeprowadzenie regresji liniowej

### Usunięcie niepoprawnych danych

```{r}
na_counts <- apply(data, 2, function(x) sum(is.na(x)))
nan_counts <- apply(data, 2, function(x) sum(is.nan(x)))
inf_counts <- apply(data, 2, function(x) sum(is.infinite(x)))

dataset <- data[complete.cases(data) & !apply(data, 1, function(x) any(is.nan(x) | is.infinite(x))), ]

na_counts <- apply(dataset, 2, function(x) sum(is.na(x)))
nan_counts <- apply(dataset, 2, function(x) sum(is.nan(x)))
inf_counts <- apply(dataset, 2, function(x) sum(is.infinite(x)))

```

### stworzenie modelu regresji liniowej

```{r}
model <- lm(Winner~ . -Match_Date -Player.Name -TeamA - TeamB,data=dataset)
summary(model)
```

### coś

```{r}
PolandSet <- dataset[dataset$Nationality == "Poland", ]
PolandSet <- PolandSet[, sapply(PolandSet, function(x) length(unique(x)) > 1)]
modelPL <- lm(Winner ~ . - Match_Date -Player.Name -TeamA - TeamB, data = PolandSet)
summary(modelPL)

```

## Regresja Logistyczna

```{r}
train_indices <- sample(nrow(dataset), 0.8 * nrow(dataset))  # 80% for training
train <- dataset[train_indices, ]
test <- dataset[-train_indices, ]
logistic <- glm(Winner ~ . - Match_Date - Nationality -Player.Name -TeamA - TeamB, family = binomial, data = train)
summary(logistic)
```

```{r}
predictions <- predict(logistic, newdata = test, type = "response")
predicted_classes <- ifelse(predictions > 0.5, 1, 0)
cm <- table(Actual = test$Winner, Predicted = predicted_classes)
print(cm)
```

```{r}
accuracy <- sum(diag(cm)) / sum(cm)
cat("Accuracy:", accuracy, "\n")

sensitivity <- cm[2, 2] / sum(cm[2, ])
cat("Sensitivity (TPR):", sensitivity, "\n")

specificity <- cm[1, 1] / sum(cm[1, ])
cat("Specificity (TNR):", specificity, "\n")
```

```{r}
library(pROC)
roc_curve <- roc(test$Winner, predictions)
plot(roc_curve, main = "ROC Curve")
```

```{r}
set.seed(0) 
train_indices <- sample(nrow(PolandSet), 0.8 * nrow(PolandSet))  # 80% for training
train_PL <- PolandSet[train_indices, ]
test_PL <- PolandSet[-train_indices, ]
logisticPL <- glm(Winner ~ . - Match_Date -Player.Name -TeamA - TeamB, family = binomial, data = train_PL)
summary(logisticPL)
```

```{r}
predictions <- predict(logisticPL, newdata = test_PL, type = "response")
predicted_classes <- ifelse(predictions > 0.5, 1, 0)
cm <- table(Actual = test_PL$Winner, Predicted = predicted_classes)
print(cm)
```

```{r}
accuracy <- sum(diag(cm)) / sum(cm)
cat("Accuracy:", accuracy, "\n")

sensitivity <- cm[2, 2] / sum(cm[2, ])
cat("Sensitivity (TPR):", sensitivity, "\n")

specificity <- cm[1, 1] / sum(cm[1, ])
cat("Specificity (TNR):", specificity, "\n")
```

```{r}
library(pROC)
roc_curve <- roc(test_PL$Winner, predictions)
plot(roc_curve, main = "ROC Curve")
```
